"use client";
import { useEffect, useState } from "react";
import type { DealStage, Locale } from "@/lib/types";

const stages: DealStage[] = ["inquiry","offer_submitted","rights_holder_review","negotiation","internal_approval","contract_draft","seller_approved","buyer_approved","signature_pending","signed","funding_pending","funded","activation_planning","creative_review","live","evidence_submitted","milestone_approved","settlement_pending","settled","performance_reporting","completed"];
const arLabels: Record<DealStage,string> = {inquiry:"استفسار",offer_submitted:"عرض مقدم",rights_holder_review:"مراجعة صاحب الحق",negotiation:"تفاوض",internal_approval:"اعتماد داخلي",contract_draft:"مسودة عقد",seller_approved:"اعتماد البائع",buyer_approved:"اعتماد المشتري",signature_pending:"بانتظار التوقيع",signed:"موقع",funding_pending:"بانتظار التمويل",funded:"ممول",activation_planning:"تخطيط التنفيذ",creative_review:"مراجعة المحتوى",live:"منشور",evidence_submitted:"أدلة التنفيذ",milestone_approved:"اعتماد المرحلة",settlement_pending:"بانتظار التسوية",settled:"مسوى",performance_reporting:"تقرير الأداء",completed:"مكتملة"};

export function DealStageClient({locale,id,initial}:{locale:Locale;id:string;initial:DealStage}) {
  const ar=locale==="ar"; const [stage,setStage]=useState(initial); const [busy,setBusy]=useState(false); const [ops,setOps]=useState<any>(null); const [error,setError]=useState("");
  const load=()=>fetch(`/api/deals/${id}/operations`).then(r=>r.json()).then(j=>setOps(j.data));
  useEffect(()=>{void load()},[]);
  async function call(action:string,payload:any={}){setBusy(true);setError("");const r=await fetch(`/api/deals/${id}/operations`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})});const j=await r.json();if(!r.ok)setError(j.error||"Failed");else{await load();if(action==="createProposal")setStage("offer_submitted");if(action==="createContract")setStage("contract_draft")}setBusy(false)}
  async function advance(){const next=stages[stages.indexOf(stage)+1];if(!next)return;setBusy(true);setError("");const r=await fetch(`/api/deals/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage:next})});const j=await r.json();if(r.ok)setStage(next);else setError(j.error||"Failed");setBusy(false)}
  async function upload(file?:File){if(!file)return;setBusy(true);setError("");const p=await fetch("/api/uploads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"presign",dealId:id,category:"proposal",fileName:file.name,contentType:file.type,sizeBytes:file.size})});const pj=await p.json();if(!p.ok){setError(pj.error||"Upload unavailable");setBusy(false);return}const put=await fetch(pj.uploadUrl,{method:"PUT",headers:pj.headers,body:file});if(!put.ok){setError("Upload failed");setBusy(false);return}await fetch("/api/uploads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",dealId:id,category:"proposal",objectKey:pj.objectKey,fileName:file.name,contentType:file.type,sizeBytes:file.size})});await load();setBusy(false)}
  const askPayment=()=>{const value=window.prompt(ar?"قيمة الدفعة بالريال":"Payment amount in SAR");if(value&&Number(value)>0)void call("recordPayment",{amount:Number(value),milestone:stage,provider:"bank_transfer"})};
  const askEmail=()=>{const to=window.prompt(ar?"البريد المستلم":"Recipient email");if(to)void call("notify",{to,subject:ar?"تحديث صفقة رعاية":"Sponsorship deal update",body:`Deal ${id.slice(0,8)}: ${stage}`})};
  const askDispute=()=>{const reason=window.prompt(ar?"سبب النزاع":"Dispute reason");if(reason)void call("openDispute",{reason,description:reason})};
  return <div>
    <div className="stage-track" style={{overflowX:"auto"}}>{stages.map((s,i)=><div key={s} className={i<=stages.indexOf(stage)?"stage active":"stage"}><span>{i+1}</span><small>{ar?arLabels[s]:s.replaceAll("_"," ")}</small></div>)}</div>
    {error&&<p className="form-error">{error}</p>}
    <div className="deal-sections">
      <div className="deal-box"><div><strong>{ar?"العرض التجاري والملفات":"Proposal & files"}</strong><p>{ops?.proposals?.length?`${ops.proposals.length} ${ar?"نسخة محفوظة":"saved version(s)"}`:(ar?"لم يقدم عرض بعد":"No proposal yet")} · {ops?.documents?.length||0} {ar?"ملف":"file(s)"}</p><button className="button button-secondary" disabled={busy} onClick={()=>call("createProposal",{amount:Number(ops?.deal?.agreed_amount||10000),deliverables:["logo placement","social mention"],timeline:["creative approval","activation","evidence"]})}>{ar?"حفظ نسخة عرض":"Save proposal version"}</button><input aria-label="Upload proposal file" type="file" accept=".pdf,.docx,image/*" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/></div></div>
      <div className="deal-box"><div><strong>{ar?"العقد والاعتمادات":"Contract & approvals"}</strong><p>{ops?.contract?.status||(ar?"لا توجد مسودة":"No draft")} · {ops?.approvals?.length||0} {ar?"اعتماد":"approval(s)"}</p><button className="button button-secondary" disabled={busy} onClick={()=>call("createContract")}>{ar?"إنشاء/تحديث المسودة":"Create/update draft"}</button><button className="button button-secondary" disabled={busy||!ops?.contract} onClick={()=>call("approve",{approvalType:"contract",decision:"approved"})}>{ar?"اعتماد العقد":"Approve contract"}</button><button className="button button-secondary" disabled={busy||!ops?.contract} onClick={()=>call("requestSignature")}>{ar?"طلب توقيع إلكتروني":"Request e-signature"}</button></div></div>
      <div className="deal-box"><div><strong>{ar?"الدفع والإشعارات والنزاع":"Payment, notices & dispute"}</strong><p>{ops?.payments?.length||0} {ar?"دفعة مسجلة":"payment record(s)"} · {ops?.outbox?.length||0} {ar?"إشعار":"notice(s)"}</p><button className="button button-secondary" disabled={busy} onClick={askPayment}>{ar?"تسجيل إثبات دفعة":"Record payment proof"}</button><button className="button button-secondary" disabled={busy} onClick={askEmail}>{ar?"إرسال تحديث":"Send update"}</button><button className="button button-secondary" disabled={busy} onClick={askDispute}>{ar?"فتح نزاع":"Open dispute"}</button></div></div>
      <div className="deal-box"><div><strong>{ar?"حالة التكاملات":"Integration status"}</strong><p>R2: {ops?.storageConfigured?"✓":"—"} · Email: {ops?.emailConfigured?"✓":"—"} · PSP: {ops?.paymentConfigured?"✓":"—"} · E-sign: {ops?.signatureConfigured?"✓":"—"}</p></div></div>
    </div>
    <button className="button button-primary" onClick={advance} disabled={busy||stage==="completed"}>{stage==="completed"?(ar?"الصفقة مكتملة":"Deal completed"):(busy?(ar?"جاري التحديث":"Updating"):(ar?"المرحلة التالية":"Next stage"))}</button>
  </div>
}
