import type { Deal, DealMessage, Notification, Opportunity, Review } from "./types";

export const demoOpportunities: Opportunity[] = [
  {
    id: "opp-cyber-forum",
    organizationId: "org-cyber",
    organizationNameAr: "ملتقى التقنية والأمن",
    organizationNameEn: "Technology & Security Forum",
    category: "events",
    titleAr: "شريك رئيسي لملتقى الأمن السيبراني 2026",
    titleEn: "Cybersecurity Forum 2026 — Main Partner",
    descriptionAr: "رعاية رئيسية تشمل الحضور التنفيذي، منصة العرض، العلامة التجارية وبيانات أداء قابلة للقياس.",
    descriptionEn: "Main sponsorship with executive audience, stage presence, branding and measurable performance data.",
    city: "Riyadh",
    startingPrice: 85000,
    currency: "SAR",
    estimatedReach: 24000,
    audience: ["CIO", "CISO", "IT Leaders", "Government"],
    formats: ["Stage", "Booth", "Branding", "Leads"],
    verified: true,
    featured: true,
    trustScore: 96,
    availabilityScore: 88,
    performanceScore: 84
  },
  {
    id: "opp-tech-podcast",
    organizationId: "org-podcast",
    organizationNameAr: "بودكاست مدار التقنية",
    organizationNameEn: "Tech Orbit Podcast",
    category: "podcasts",
    titleAr: "رعاية 4 حلقات في بودكاست تقني سعودي",
    titleEn: "Sponsor 4 episodes of a Saudi technology podcast",
    descriptionAr: "حزمة صوتية ورقمية تستهدف صناع القرار والمهنيين التقنيين في المملكة.",
    descriptionEn: "Audio and digital package targeting Saudi technology professionals and decision makers.",
    city: "Riyadh",
    startingPrice: 24000,
    currency: "SAR",
    estimatedReach: 92000,
    audience: ["Technology", "Professionals", "Founders"],
    formats: ["Host-read", "Social clip", "Newsletter"],
    verified: true,
    featured: true,
    trustScore: 92,
    availabilityScore: 95,
    performanceScore: 90
  },
  {
    id: "opp-linkedin-creator",
    organizationId: "org-creator",
    organizationNameAr: "صانع محتوى أعمال وتقنية",
    organizationNameEn: "Business & Tech Creator",
    category: "creators",
    titleAr: "حملة LinkedIn قيادية لصناع القرار",
    titleEn: "Executive LinkedIn campaign for decision makers",
    descriptionAr: "محتوى ثنائي اللغة يركز على الأعمال والتحول الرقمي مع جمهور سعودي مهني.",
    descriptionEn: "Bilingual business and digital-transformation content with a Saudi professional audience.",
    city: "Riyadh",
    startingPrice: 9500,
    currency: "SAR",
    estimatedReach: 65000,
    audience: ["Executives", "Technology", "Business"],
    formats: ["Post", "Carousel", "Video"],
    verified: true,
    trustScore: 94,
    availabilityScore: 90,
    performanceScore: 86
  },
  {
    id: "opp-esports",
    organizationId: "org-esports",
    organizationNameAr: "دوري الألعاب السعودي",
    organizationNameEn: "Saudi Gaming League",
    category: "gaming",
    titleAr: "شريك بطولة ألعاب إلكترونية",
    titleEn: "Esports tournament partner",
    descriptionAr: "رعاية بطولة حضورية ورقمية مع تفعيل جماهيري ومحتوى مباشر.",
    descriptionEn: "Live and digital esports sponsorship with fan activation and streaming content.",
    city: "Riyadh",
    startingPrice: 45000,
    currency: "SAR",
    estimatedReach: 410000,
    audience: ["Gen Z", "Gaming", "Students"],
    formats: ["Stream", "Arena branding", "Activation"],
    verified: true,
    trustScore: 88,
    availabilityScore: 80,
    performanceScore: 92
  },
  {
    id: "opp-university",
    organizationId: "org-community",
    organizationNameAr: "مجتمع جامعي للابتكار",
    organizationNameEn: "University Innovation Community",
    category: "community",
    titleAr: "رعاية أسبوع الابتكار الجامعي",
    titleEn: "University Innovation Week sponsorship",
    descriptionAr: "وصول مباشر للطلاب والخريجين ورواد الأعمال عبر أنشطة وورش وتجارب علامة تجارية.",
    descriptionEn: "Direct access to students, graduates and founders through workshops and brand activations.",
    city: "Riyadh",
    startingPrice: 18000,
    currency: "SAR",
    estimatedReach: 15000,
    audience: ["Students", "Graduates", "Founders"],
    formats: ["Workshop", "Booth", "Challenge"],
    verified: true,
    trustScore: 91,
    availabilityScore: 93,
    performanceScore: 78
  },
  {
    id: "opp-app",
    organizationId: "org-app",
    organizationNameAr: "تطبيق حياة الرياض",
    organizationNameEn: "Riyadh Life App",
    category: "digital",
    titleAr: "حزمة ظهور داخل تطبيق محلي",
    titleEn: "In-app local reach package",
    descriptionAr: "ظهور داخل التطبيق وإشعارات موجهة ومواضع أصلية قابلة للقياس.",
    descriptionEn: "In-app placements, targeted notifications and measurable native inventory.",
    city: "Riyadh",
    startingPrice: 12000,
    currency: "SAR",
    estimatedReach: 180000,
    audience: ["Consumers", "Riyadh", "Mobile"],
    formats: ["Banner", "Native", "Push"],
    verified: true,
    trustScore: 90,
    availabilityScore: 86,
    performanceScore: 82
  },
  {
    id: "opp-ooh",
    organizationId: "org-ooh",
    organizationNameAr: "شبكة شاشات المدينة",
    organizationNameEn: "City Screen Network",
    category: "ooh",
    titleAr: "شاشات رقمية في مواقع أعمال بالرياض",
    titleEn: "Digital screens in Riyadh business locations",
    descriptionAr: "شبكة شاشات في مواقع ذات كثافة مهنية مع جدولة مرنة للحملات.",
    descriptionEn: "Digital screen network in professional high-footfall locations with flexible scheduling.",
    city: "Riyadh",
    startingPrice: 16000,
    currency: "SAR",
    estimatedReach: 260000,
    audience: ["Professionals", "Commuters", "Business"],
    formats: ["DOOH", "15s spot", "Dayparting"],
    verified: true,
    trustScore: 89,
    availabilityScore: 84,
    performanceScore: 80
  },
  {
    id: "opp-sports",
    organizationId: "org-sports",
    organizationNameAr: "نادي رياضي مجتمعي",
    organizationNameEn: "Community Sports Club",
    category: "sports",
    titleAr: "شريك موسم رياضي مجتمعي",
    titleEn: "Community sports season partner",
    descriptionAr: "رعاية موسم تشمل الفرق والفعاليات والمحتوى الرقمي والتفعيل الجماهيري.",
    descriptionEn: "Season sponsorship across teams, events, digital content and fan activation.",
    city: "Jeddah",
    startingPrice: 35000,
    currency: "SAR",
    estimatedReach: 120000,
    audience: ["Families", "Sports", "Youth"],
    formats: ["Jersey", "Events", "Social"],
    verified: true,
    trustScore: 87,
    availabilityScore: 82,
    performanceScore: 85
  },
  // New opportunities — more cities and categories
  {
    id: "opp-jeddah-food-fest",
    organizationId: "org-jeddah-events",
    organizationNameAr: "مهرجان جدة للطعام",
    organizationNameEn: "Jeddah Food Festival",
    category: "events",
    titleAr: "شريك رئيسي لمهرجان جدة للطعام 2026",
    titleEn: "Jeddah Food Festival 2026 — Title Sponsor",
    descriptionAr: "رعاية شاملة لمهرجان طعام على الواجهة البحرية مع 80+ مطعم وفعاليات طهي حية.",
    descriptionEn: "Full-scale sponsorship of a waterfront food festival with 80+ restaurants and live culinary events.",
    city: "Jeddah",
    startingPrice: 120000,
    currency: "SAR",
    estimatedReach: 350000,
    audience: ["Families", "Foodies", "Consumers", "Tourism"],
    formats: ["Title branding", "Activation zone", "Social", "Sampling"],
    verified: true,
    featured: true,
    trustScore: 94,
    availabilityScore: 75,
    performanceScore: 91
  },
  {
    id: "opp-dammam-tech-hub",
    organizationId: "org-eastern",
    organizationNameAr: "مركز الابتكار الشرقي",
    organizationNameEn: "Eastern Innovation Hub",
    category: "community",
    titleAr: "شراكة مساحة ابتكار في الدمام",
    titleEn: "Dammam Innovation Hub Partnership",
    descriptionAr: "شراكة سنوية مع مساحة عمل وابتكار تستقطب رواد أعمال ومطورين من المنطقة الشرقية.",
    descriptionEn: "Annual partnership with a coworking and innovation space for Eastern Province entrepreneurs.",
    city: "Dammam",
    startingPrice: 22000,
    currency: "SAR",
    estimatedReach: 18000,
    audience: ["Founders", "Developers", "Technology"],
    formats: ["Naming rights", "Events", "Mentorship"],
    verified: true,
    trustScore: 88,
    availabilityScore: 92,
    performanceScore: 76
  },
  {
    id: "opp-makkah-hajj-app",
    organizationId: "org-hajj-digital",
    organizationNameAr: "تطبيق خدمات الحج الذكي",
    organizationNameEn: "Smart Hajj Services App",
    category: "digital",
    titleAr: "إعلانات داخل تطبيق خدمات الحج والعمرة",
    titleEn: "In-app ads in Hajj & Umrah services app",
    descriptionAr: "وصول حصري لملايين المستخدمين خلال مواسم الحج والعمرة عبر إعلانات مواقع أصلية.",
    descriptionEn: "Exclusive reach to millions of users during Hajj and Umrah seasons via native ad placements.",
    city: "Makkah",
    startingPrice: 65000,
    currency: "SAR",
    estimatedReach: 2500000,
    audience: ["Pilgrims", "Travelers", "Consumers", "International"],
    formats: ["Native", "Banner", "Push", "Sponsored content"],
    verified: true,
    trustScore: 95,
    availabilityScore: 70,
    performanceScore: 88
  },
  {
    id: "opp-madinah-cultural",
    organizationId: "org-madinah-culture",
    organizationNameAr: "جمعية المدينة الثقافية",
    organizationNameEn: "Madinah Cultural Society",
    category: "events",
    titleAr: "رعاية مهرجان المدينة الثقافي",
    titleEn: "Madinah Cultural Festival Sponsorship",
    descriptionAr: "مهرجان ثقافي يجمع الفنون والتراث والمعارض مع جمهور عائلي متنوع.",
    descriptionEn: "Cultural festival blending arts, heritage and exhibitions for a diverse family audience.",
    city: "Madinah",
    startingPrice: 40000,
    currency: "SAR",
    estimatedReach: 95000,
    audience: ["Families", "Culture", "Tourism", "Youth"],
    formats: ["Booth", "Stage", "Branding", "Print"],
    verified: true,
    trustScore: 90,
    availabilityScore: 85,
    performanceScore: 82
  },
  {
    id: "opp-khobar-fitness",
    organizationId: "org-fitness",
    organizationNameAr: "تجمع الخبر الرياضي",
    organizationNameEn: "Khobar Fitness Community",
    category: "sports",
    titleAr: "رعاية سباق نصف ماراثون الخبر",
    titleEn: "Khobar Half Marathon Sponsorship",
    descriptionAr: "سباق مجتمعي يضم 5,000 مشارك مع تفعيل للعلامة التجارية على المسار والحدث.",
    descriptionEn: "Community run with 5,000 participants plus brand activation along the course and event area.",
    city: "Khobar",
    startingPrice: 28000,
    currency: "SAR",
    estimatedReach: 45000,
    audience: ["Athletes", "Fitness", "Families", "Health"],
    formats: ["Course branding", "Finish line", "Goodie bag", "Social"],
    verified: true,
    trustScore: 86,
    availabilityScore: 90,
    performanceScore: 83
  },
  {
    id: "opp-youtube-creator",
    organizationId: "org-yt-creator",
    organizationNameAr: "قناة مراجعات تقنية",
    organizationNameEn: "TechReview Arabia",
    category: "creators",
    titleAr: "رعاية 3 فيديوهات مراجعات تقنية على يوتيوب",
    titleEn: "Sponsor 3 YouTube tech review videos",
    descriptionAr: "محتوى مراجعات تقنية باللغة العربية مع جمهور خليجي شاب ومتفاعل.",
    descriptionEn: "Arabic tech review content with an engaged young GCC audience on YouTube.",
    city: "Riyadh",
    startingPrice: 15000,
    currency: "SAR",
    estimatedReach: 520000,
    audience: ["Gen Z", "Technology", "Consumers", "Students"],
    formats: ["Integration", "Dedicated video", "Community post"],
    verified: true,
    trustScore: 91,
    availabilityScore: 88,
    performanceScore: 93
  },
  {
    id: "opp-jeddah-ooh",
    organizationId: "org-jeddah-screens",
    organizationNameAr: "شاشات كورنيش جدة",
    organizationNameEn: "Jeddah Corniche Screens",
    category: "ooh",
    titleAr: "لوحات رقمية على كورنيش جدة",
    titleEn: "Digital billboards on Jeddah Corniche",
    descriptionAr: "شبكة لوحات رقمية على كورنيش جدة مع جمهور عائلي وسياحي عالي الكثافة.",
    descriptionEn: "Premium digital billboard network along Jeddah Corniche with high family and tourist traffic.",
    city: "Jeddah",
    startingPrice: 55000,
    currency: "SAR",
    estimatedReach: 800000,
    audience: ["Families", "Tourists", "Consumers", "Commuters"],
    formats: ["DOOH", "30s spot", "Dayparting", "Animated"],
    verified: true,
    trustScore: 93,
    availabilityScore: 78,
    performanceScore: 87
  },
  {
    id: "opp-podcast-business",
    organizationId: "org-biz-podcast",
    organizationNameAr: "بودكاست ريادة الأعمال",
    organizationNameEn: "Entrepreneurship Podcast SA",
    category: "podcasts",
    titleAr: "رعاية موسم كامل لبودكاست ريادة الأعمال",
    titleEn: "Full season sponsorship of entrepreneurship podcast",
    descriptionAr: "12 حلقة تستضيف مؤسسين ومستثمرين مع جمهور سعودي مهتم بريادة الأعمال.",
    descriptionEn: "12 episodes featuring founders and investors, targeting Saudi startup-interested audience.",
    city: "Riyadh",
    startingPrice: 48000,
    currency: "SAR",
    estimatedReach: 150000,
    audience: ["Founders", "Investors", "Business", "Executives"],
    formats: ["Host-read", "Pre-roll", "Newsletter", "Social clip"],
    verified: true,
    trustScore: 90,
    availabilityScore: 82,
    performanceScore: 88
  },
  {
    id: "opp-tabuk-adventure",
    organizationId: "org-tabuk-tourism",
    organizationNameAr: "سياحة تبوك للمغامرات",
    organizationNameEn: "Tabuk Adventure Tourism",
    category: "events",
    titleAr: "رعاية رالي الصحراء السياحي في تبوك",
    titleEn: "Tabuk Desert Rally Tourism Sponsorship",
    descriptionAr: "رالي مغامرات في صحراء تبوك مع تغطية إعلامية واسعة وجمهور سياحي دولي.",
    descriptionEn: "Adventure rally in Tabuk desert with broad media coverage and international tourism audience.",
    city: "Tabuk",
    startingPrice: 70000,
    currency: "SAR",
    estimatedReach: 200000,
    audience: ["Adventure", "Tourism", "International", "Youth"],
    formats: ["Title sponsor", "Vehicle branding", "Livestream", "Social"],
    verified: true,
    trustScore: 85,
    availabilityScore: 88,
    performanceScore: 79
  },
  {
    id: "opp-gaming-streamer",
    organizationId: "org-streamer",
    organizationNameAr: "ستريمر ألعاب عربي",
    organizationNameEn: "ArabGamer Streamer",
    category: "gaming",
    titleAr: "رعاية بثوث مباشرة لستريمر ألعاب",
    titleEn: "Live stream sponsorship with top Arab gamer",
    descriptionAr: "بثوث مباشرة على تويتش ويوتيوب مع جمهور عربي شاب ومتفاعل في الألعاب.",
    descriptionEn: "Twitch & YouTube live streams with an engaged young Arab gaming audience.",
    city: "Jeddah",
    startingPrice: 20000,
    currency: "SAR",
    estimatedReach: 380000,
    audience: ["Gen Z", "Gaming", "Youth", "Students"],
    formats: ["Stream overlay", "Shoutout", "Giveaway", "Social"],
    verified: true,
    trustScore: 84,
    availabilityScore: 91,
    performanceScore: 90
  }
];

export const demoDeals: Deal[] = [
  {
    id: "deal-001",
    opportunityId: "opp-tech-podcast",
    campaignId: "camp-001",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-podcast",
    title: "Tech Orbit — Q4 Thought Leadership",
    counterparty: "Tech Orbit Podcast",
    amount: 24000,
    currency: "SAR",
    stage: "negotiation",
    updatedAt: "2026-08-14T11:30:00Z"
  },
  {
    id: "deal-002",
    opportunityId: "opp-university",
    campaignId: "camp-001",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-community",
    title: "Innovation Week activation",
    counterparty: "University Innovation Community",
    amount: 18000,
    currency: "SAR",
    stage: "approval",
    updatedAt: "2026-08-13T08:15:00Z"
  },
  {
    id: "deal-003",
    opportunityId: "opp-youtube-creator",
    campaignId: "camp-002",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-yt-creator",
    title: "TechReview Arabia — Product Launch",
    counterparty: "TechReview Arabia",
    amount: 15000,
    currency: "SAR",
    stage: "contract",
    updatedAt: "2026-08-12T14:00:00Z"
  },
  {
    id: "deal-004",
    opportunityId: "opp-jeddah-food-fest",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-jeddah-events",
    title: "Jeddah Food Fest — Brand Activation",
    counterparty: "Jeddah Food Festival",
    amount: 120000,
    currency: "SAR",
    stage: "payment",
    updatedAt: "2026-08-10T09:45:00Z"
  },
  {
    id: "deal-005",
    opportunityId: "opp-esports",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-esports",
    title: "Saudi Gaming League — Summer Cup",
    counterparty: "Saudi Gaming League",
    amount: 45000,
    currency: "SAR",
    stage: "completed",
    updatedAt: "2026-07-28T16:20:00Z"
  }
];

export const demoNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "deal_update",
    titleAr: "تحديث صفقة",
    titleEn: "Deal Update",
    bodyAr: "صفقة Tech Orbit انتقلت إلى مرحلة التفاوض",
    bodyEn: "Tech Orbit deal moved to negotiation stage",
    read: false,
    createdAt: "2026-08-14T11:30:00Z",
    link: "/deals/deal-001"
  },
  {
    id: "notif-2",
    type: "new_match",
    titleAr: "فرصة مطابقة جديدة",
    titleEn: "New Match Found",
    bodyAr: "تم العثور على 3 فرص جديدة تتطابق مع حملتك",
    bodyEn: "3 new opportunities match your campaign criteria",
    read: false,
    createdAt: "2026-08-14T09:00:00Z",
    link: "/planner"
  },
  {
    id: "notif-3",
    type: "verification",
    titleAr: "تحقق مكتمل",
    titleEn: "Verification Complete",
    bodyAr: "تم التحقق من جهة بودكاست مدار التقنية بنجاح",
    bodyEn: "Tech Orbit Podcast organization verification completed",
    read: true,
    createdAt: "2026-08-13T15:00:00Z"
  },
  {
    id: "notif-4",
    type: "deal_update",
    titleAr: "عرض جديد مستلم",
    titleEn: "New Proposal Received",
    bodyAr: "تلقيت عرضًا جديدًا لصفقة Innovation Week",
    bodyEn: "New proposal received for Innovation Week deal",
    read: true,
    createdAt: "2026-08-12T10:00:00Z",
    link: "/deals/deal-002"
  },
  {
    id: "notif-5",
    type: "system",
    titleAr: "مرحبًا بك في SponsorLoop",
    titleEn: "Welcome to SponsorLoop",
    bodyAr: "ابدأ باستكشاف الفرص أو أنشئ حملتك الأولى",
    bodyEn: "Start by exploring opportunities or creating your first campaign",
    read: true,
    createdAt: "2026-08-10T08:00:00Z"
  }
];

export const demoDealMessages: DealMessage[] = [
  {
    id: "msg-1",
    dealId: "deal-001",
    senderName: "Tech Orbit Podcast",
    senderRole: "seller",
    message: "Thank you for your interest. We can offer a bonus social clip package for the 4-episode deal.",
    createdAt: "2026-08-14T11:30:00Z"
  },
  {
    id: "msg-2",
    dealId: "deal-001",
    senderName: "Demo Brand",
    senderRole: "buyer",
    message: "That sounds great. Can you share the audience demographics breakdown?",
    createdAt: "2026-08-14T10:15:00Z"
  },
  {
    id: "msg-3",
    dealId: "deal-001",
    senderName: "System",
    senderRole: "system",
    message: "Deal created and moved to negotiation stage.",
    createdAt: "2026-08-13T16:00:00Z"
  },
  {
    id: "msg-4",
    dealId: "deal-002",
    senderName: "University Innovation Community",
    senderRole: "seller",
    message: "We have confirmed the booth location and workshop slot for your team.",
    createdAt: "2026-08-13T08:15:00Z"
  },
  {
    id: "msg-5",
    dealId: "deal-002",
    senderName: "System",
    senderRole: "system",
    message: "Deal advanced to approval stage.",
    createdAt: "2026-08-12T14:00:00Z"
  }
];

export const demoReviews: Review[] = [
  {
    id: "rev-1",
    dealId: "deal-005",
    rating: 5,
    comment: "Excellent partnership! Great audience engagement and professional execution.",
    reviewerName: "Demo Brand",
    createdAt: "2026-07-29T10:00:00Z"
  }
];
