import type { Deal, DealMessage, Notification, Opportunity, PackageTier, Review, SponsorshipRequest, SuccessStory } from "./types";

export const demoOpportunities: Opportunity[] = [
  {
    id: "opp-cyber-forum",
    organizationId: "org-cyber",
    organizationNameAr: "ملتقى التقنية والأمن",
    organizationNameEn: "Technology & Security Forum",
    category: "events",
    titleAr: "شريك رئيسي لملتقى الأمن السيبراني 2026",
    titleEn: "Cybersecurity Forum 2026 — Main Partner",
    descriptionAr: "رعاية رئيسية تشمل الحضور التنفيذي، منصة العرض، العلامة التجارية وبيانات أداء قابلة للقياس.",
    descriptionEn: "Main sponsorship with executive audience, stage presence, branding and measurable performance data.",
    city: "Riyadh",
    startingPrice: 85000,
    currency: "SAR",
    estimatedReach: 24000,
    audience: ["CIO", "CISO", "IT Leaders", "Government"],
    formats: ["Stage", "Booth", "Branding", "Leads"],
    verified: true,
    featured: true,
    trustScore: 96,
    availabilityScore: 88,
    performanceScore: 84
  },
  {
    id: "opp-tech-podcast",
    organizationId: "org-podcast",
    organizationNameAr: "بودكاست مدار التقنية",
    organizationNameEn: "Tech Orbit Podcast",
    category: "podcasts",
    titleAr: "رعاية 4 حلقات في بودكاست تقني سعودي",
    titleEn: "Sponsor 4 episodes of a Saudi technology podcast",
    descriptionAr: "حزمة صوتية ورقمية تستهدف صناع القرار والمهنيين التقنيين في المملكة.",
    descriptionEn: "Audio and digital package targeting Saudi technology professionals and decision makers.",
    city: "Riyadh",
    startingPrice: 24000,
    currency: "SAR",
    estimatedReach: 92000,
    audience: ["Technology", "Professionals", "Founders"],
    formats: ["Host-read", "Social clip", "Newsletter"],
    verified: true,
    featured: true,
    trustScore: 92,
    availabilityScore: 95,
    performanceScore: 90
  },
  {
    id: "opp-linkedin-creator",
    organizationId: "org-creator",
    organizationNameAr: "صانع محتوى أعمال وتقنية",
    organizationNameEn: "Business & Tech Creator",
    category: "creators",
    titleAr: "حملة LinkedIn قيادية لصناع القرار",
    titleEn: "Executive LinkedIn campaign for decision makers",
    descriptionAr: "محتوى ثنائي اللغة يركز على الأعمال والتحول الرقمي مع جمهور سعودي مهني.",
    descriptionEn: "Bilingual business and digital-transformation content with a Saudi professional audience.",
    city: "Riyadh",
    startingPrice: 9500,
    currency: "SAR",
    estimatedReach: 65000,
    audience: ["Executives", "Technology", "Business"],
    formats: ["Post", "Carousel", "Video"],
    verified: true,
    trustScore: 94,
    availabilityScore: 90,
    performanceScore: 86
  },
  {
    id: "opp-esports",
    organizationId: "org-esports",
    organizationNameAr: "دوري الألعاب السعودي",
    organizationNameEn: "Saudi Gaming League",
    category: "gaming",
    titleAr: "شريك بطولة ألعاب إلكترونية",
    titleEn: "Esports tournament partner",
    descriptionAr: "رعاية بطولة حضورية ورقمية مع تفعيل جماهيري ومحتوى مباشر.",
    descriptionEn: "Live and digital esports sponsorship with fan activation and streaming content.",
    city: "Riyadh",
    startingPrice: 45000,
    currency: "SAR",
    estimatedReach: 410000,
    audience: ["Gen Z", "Gaming", "Students"],
    formats: ["Stream", "Arena branding", "Activation"],
    verified: true,
    trustScore: 88,
    availabilityScore: 80,
    performanceScore: 92
  },
  {
    id: "opp-university",
    organizationId: "org-community",
    organizationNameAr: "مجتمع جامعي للابتكار",
    organizationNameEn: "University Innovation Community",
    category: "community",
    titleAr: "رعاية أسبوع الابتكار الجامعي",
    titleEn: "University Innovation Week sponsorship",
    descriptionAr: "وصول مباشر للطلاب والخريجين ورواد الأعمال عبر أنشطة وورش وتجارب علامة تجارية.",
    descriptionEn: "Direct access to students, graduates and founders through workshops and brand activations.",
    city: "Riyadh",
    startingPrice: 18000,
    currency: "SAR",
    estimatedReach: 15000,
    audience: ["Students", "Graduates", "Founders"],
    formats: ["Workshop", "Booth", "Challenge"],
    verified: true,
    trustScore: 91,
    availabilityScore: 93,
    performanceScore: 78
  },
  {
    id: "opp-app",
    organizationId: "org-app",
    organizationNameAr: "تطبيق حياة الرياض",
    organizationNameEn: "Riyadh Life App",
    category: "digital",
    titleAr: "حزمة ظهور داخل تطبيق محلي",
    titleEn: "In-app local reach package",
    descriptionAr: "ظهور داخل التطبيق وإشعارات موجهة ومواضع أصلية قابلة للقياس.",
    descriptionEn: "In-app placements, targeted notifications and measurable native inventory.",
    city: "Riyadh",
    startingPrice: 12000,
    currency: "SAR",
    estimatedReach: 180000,
    audience: ["Consumers", "Riyadh", "Mobile"],
    formats: ["Banner", "Native", "Push"],
    verified: true,
    trustScore: 90,
    availabilityScore: 86,
    performanceScore: 82
  },
  {
    id: "opp-ooh",
    organizationId: "org-ooh",
    organizationNameAr: "شبكة شاشات المدينة",
    organizationNameEn: "City Screen Network",
    category: "ooh",
    titleAr: "شاشات رقمية في مواقع أعمال بالرياض",
    titleEn: "Digital screens in Riyadh business locations",
    descriptionAr: "شبكة شاشات في مواقع ذات كثافة مهنية مع جدولة مرنة للحملات.",
    descriptionEn: "Digital screen network in professional high-footfall locations with flexible scheduling.",
    city: "Riyadh",
    startingPrice: 16000,
    currency: "SAR",
    estimatedReach: 260000,
    audience: ["Professionals", "Commuters", "Business"],
    formats: ["DOOH", "15s spot", "Dayparting"],
    verified: true,
    trustScore: 89,
    availabilityScore: 84,
    performanceScore: 80
  },
  {
    id: "opp-sports",
    organizationId: "org-sports",
    organizationNameAr: "نادي رياضي مجتمعي",
    organizationNameEn: "Community Sports Club",
    category: "sports",
    titleAr: "شريك موسم رياضي مجتمعي",
    titleEn: "Community sports season partner",
    descriptionAr: "رعاية موسم تشمل الفرق والفعاليات والمحتوى الرقمي والتفعيل الجماهيري.",
    descriptionEn: "Season sponsorship across teams, events, digital content and fan activation.",
    city: "Jeddah",
    startingPrice: 35000,
    currency: "SAR",
    estimatedReach: 120000,
    audience: ["Families", "Sports", "Youth"],
    formats: ["Jersey", "Events", "Social"],
    verified: true,
    trustScore: 87,
    availabilityScore: 82,
    performanceScore: 85
  },
  // New opportunities — more cities and categories
  {
    id: "opp-jeddah-food-fest",
    organizationId: "org-jeddah-events",
    organizationNameAr: "مهرجان جدة للطعام",
    organizationNameEn: "Jeddah Food Festival",
    category: "events",
    titleAr: "شريك رئيسي لمهرجان جدة للطعام 2026",
    titleEn: "Jeddah Food Festival 2026 — Title Sponsor",
    descriptionAr: "رعاية شاملة لمهرجان طعام على الواجهة البحرية مع 80+ مطعم وفعاليات طهي حية.",
    descriptionEn: "Full-scale sponsorship of a waterfront food festival with 80+ restaurants and live culinary events.",
    city: "Jeddah",
    startingPrice: 120000,
    currency: "SAR",
    estimatedReach: 350000,
    audience: ["Families", "Foodies", "Consumers", "Tourism"],
    formats: ["Title branding", "Activation zone", "Social", "Sampling"],
    verified: true,
    featured: true,
    trustScore: 94,
    availabilityScore: 75,
    performanceScore: 91
  },
  {
    id: "opp-dammam-tech-hub",
    organizationId: "org-eastern",
    organizationNameAr: "مركز الابتكار الشرقي",
    organizationNameEn: "Eastern Innovation Hub",
    category: "community",
    titleAr: "شراكة مساحة ابتكار في الدمام",
    titleEn: "Dammam Innovation Hub Partnership",
    descriptionAr: "شراكة سنوية مع مساحة عمل وابتكار تستقطب رواد أعمال ومطورين من المنطقة الشرقية.",
    descriptionEn: "Annual partnership with a coworking and innovation space for Eastern Province entrepreneurs.",
    city: "Dammam",
    startingPrice: 22000,
    currency: "SAR",
    estimatedReach: 18000,
    audience: ["Founders", "Developers", "Technology"],
    formats: ["Naming rights", "Events", "Mentorship"],
    verified: true,
    trustScore: 88,
    availabilityScore: 92,
    performanceScore: 76
  },
  {
    id: "opp-makkah-hajj-app",
    organizationId: "org-hajj-digital",
    organizationNameAr: "تطبيق خدمات الحج الذكي",
    organizationNameEn: "Smart Hajj Services App",
    category: "digital",
    titleAr: "إعلانات داخل تطبيق خدمات الحج والعمرة",
    titleEn: "In-app ads in Hajj & Umrah services app",
    descriptionAr: "وصول حصري لملايين المستخدمين خلال مواسم الحج والعمرة عبر إعلانات مواقع أصلية.",
    descriptionEn: "Exclusive reach to millions of users during Hajj and Umrah seasons via native ad placements.",
    city: "Makkah",
    startingPrice: 65000,
    currency: "SAR",
    estimatedReach: 2500000,
    audience: ["Pilgrims", "Travelers", "Consumers", "International"],
    formats: ["Native", "Banner", "Push", "Sponsored content"],
    verified: true,
    trustScore: 95,
    availabilityScore: 70,
    performanceScore: 88
  },
  {
    id: "opp-madinah-cultural",
    organizationId: "org-madinah-culture",
    organizationNameAr: "جمعية المدينة الثقافية",
    organizationNameEn: "Madinah Cultural Society",
    category: "events",
    titleAr: "رعاية مهرجان المدينة الثقافي",
    titleEn: "Madinah Cultural Festival Sponsorship",
    descriptionAr: "مهرجان ثقافي يجمع الفنون والتراث والمعارض مع جمهور عائلي متنوع.",
    descriptionEn: "Cultural festival blending arts, heritage and exhibitions for a diverse family audience.",
    city: "Madinah",
    startingPrice: 40000,
    currency: "SAR",
    estimatedReach: 95000,
    audience: ["Families", "Culture", "Tourism", "Youth"],
    formats: ["Booth", "Stage", "Branding", "Print"],
    verified: true,
    trustScore: 90,
    availabilityScore: 85,
    performanceScore: 82
  },
  {
    id: "opp-khobar-fitness",
    organizationId: "org-fitness",
    organizationNameAr: "تجمع الخبر الرياضي",
    organizationNameEn: "Khobar Fitness Community",
    category: "sports",
    titleAr: "رعاية سباق نصف ماراثون الخبر",
    titleEn: "Khobar Half Marathon Sponsorship",
    descriptionAr: "سباق مجتمعي يضم 5,000 مشارك مع تفعيل للعلامة التجارية على المسار والحدث.",
    descriptionEn: "Community run with 5,000 participants plus brand activation along the course and event area.",
    city: "Khobar",
    startingPrice: 28000,
    currency: "SAR",
    estimatedReach: 45000,
    audience: ["Athletes", "Fitness", "Families", "Health"],
    formats: ["Course branding", "Finish line", "Goodie bag", "Social"],
    verified: true,
    trustScore: 86,
    availabilityScore: 90,
    performanceScore: 83
  },
  {
    id: "opp-youtube-creator",
    organizationId: "org-yt-creator",
    organizationNameAr: "قناة مراجعات تقنية",
    organizationNameEn: "TechReview Arabia",
    category: "creators",
    titleAr: "رعاية 3 فيديوهات مراجعات تقنية على يوتيوب",
    titleEn: "Sponsor 3 YouTube tech review videos",
    descriptionAr: "محتوى مراجعات تقنية باللغة العربية مع جمهور خليجي شاب ومتفاعل.",
    descriptionEn: "Arabic tech review content with an engaged young GCC audience on YouTube.",
    city: "Riyadh",
    startingPrice: 15000,
    currency: "SAR",
    estimatedReach: 520000,
    audience: ["Gen Z", "Technology", "Consumers", "Students"],
    formats: ["Integration", "Dedicated video", "Community post"],
    verified: true,
    trustScore: 91,
    availabilityScore: 88,
    performanceScore: 93
  },
  {
    id: "opp-jeddah-ooh",
    organizationId: "org-jeddah-screens",
    organizationNameAr: "شاشات كورنيش جدة",
    organizationNameEn: "Jeddah Corniche Screens",
    category: "ooh",
    titleAr: "لوحات رقمية على كورنيش جدة",
    titleEn: "Digital billboards on Jeddah Corniche",
    descriptionAr: "شبكة لوحات رقمية على كورنيش جدة مع جمهور عائلي وسياحي عالي الكثافة.",
    descriptionEn: "Premium digital billboard network along Jeddah Corniche with high family and tourist traffic.",
    city: "Jeddah",
    startingPrice: 55000,
    currency: "SAR",
    estimatedReach: 800000,
    audience: ["Families", "Tourists", "Consumers", "Commuters"],
    formats: ["DOOH", "30s spot", "Dayparting", "Animated"],
    verified: true,
    trustScore: 93,
    availabilityScore: 78,
    performanceScore: 87
  },
  {
    id: "opp-podcast-business",
    organizationId: "org-biz-podcast",
    organizationNameAr: "بودكاست ريادة الأعمال",
    organizationNameEn: "Entrepreneurship Podcast SA",
    category: "podcasts",
    titleAr: "رعاية موسم كامل لبودكاست ريادة الأعمال",
    titleEn: "Full season sponsorship of entrepreneurship podcast",
    descriptionAr: "12 حلقة تستضيف مؤسسين ومستثمرين مع جمهور سعودي مهتم بريادة الأعمال.",
    descriptionEn: "12 episodes featuring founders and investors, targeting Saudi startup-interested audience.",
    city: "Riyadh",
    startingPrice: 48000,
    currency: "SAR",
    estimatedReach: 150000,
    audience: ["Founders", "Investors", "Business", "Executives"],
    formats: ["Host-read", "Pre-roll", "Newsletter", "Social clip"],
    verified: true,
    trustScore: 90,
    availabilityScore: 82,
    performanceScore: 88
  },
  {
    id: "opp-tabuk-adventure",
    organizationId: "org-tabuk-tourism",
    organizationNameAr: "سياحة تبوك للمغامرات",
    organizationNameEn: "Tabuk Adventure Tourism",
    category: "events",
    titleAr: "رعاية رالي الصحراء السياحي في تبوك",
    titleEn: "Tabuk Desert Rally Tourism Sponsorship",
    descriptionAr: "رالي مغامرات في صحراء تبوك مع تغطية إعلامية واسعة وجمهور سياحي دولي.",
    descriptionEn: "Adventure rally in Tabuk desert with broad media coverage and international tourism audience.",
    city: "Tabuk",
    startingPrice: 70000,
    currency: "SAR",
    estimatedReach: 200000,
    audience: ["Adventure", "Tourism", "International", "Youth"],
    formats: ["Title sponsor", "Vehicle branding", "Livestream", "Social"],
    verified: true,
    trustScore: 85,
    availabilityScore: 88,
    performanceScore: 79
  },
  {
    id: "opp-athlete-swimmer",
    organizationId: "org-athlete-1",
    organizationNameAr: "سارة الحربي — سباحة أولمبية",
    organizationNameEn: "Sara Al-Harbi — Olympic Swimmer",
    category: "athletes",
    titleAr: "رعاية رياضية فردية لسباحة سعودية أولمبية",
    titleEn: "Individual athlete sponsorship — Saudi Olympic swimmer",
    descriptionAr: "رعاية رياضية مباشرة تشمل ظهور العلامة على الملابس والمحتوى الاجتماعي والمشاركة في فعاليات الراعي.",
    descriptionEn: "Direct athlete sponsorship with kit branding, social content and sponsor event appearances.",
    city: "Jeddah",
    startingPrice: 60000,
    currency: "SAR",
    estimatedReach: 280000,
    audience: ["Sports", "Youth", "Fitness", "Women"],
    formats: ["Kit branding", "Social posts", "Event appearance", "Video"],
    verified: true,
    featured: true,
    trustScore: 93,
    availabilityScore: 85,
    performanceScore: 91
  },
  {
    id: "opp-athlete-footballer",
    organizationId: "org-athlete-2",
    organizationNameAr: "خالد المولد — لاعب كرة قدم",
    organizationNameEn: "Khalid Al-Muwallad — Football Player",
    category: "athletes",
    titleAr: "شراكة مع لاعب كرة قدم سعودي بارز",
    titleEn: "Partnership with prominent Saudi football player",
    descriptionAr: "شراكة تشمل المحتوى الرقمي وحضور فعاليات العلامة التجارية وحملات التواصل الاجتماعي.",
    descriptionEn: "Partnership includes digital content, brand event attendance and social media campaigns.",
    city: "Riyadh",
    startingPrice: 150000,
    currency: "SAR",
    estimatedReach: 1200000,
    audience: ["Sports", "Youth", "Gen Z", "Families"],
    formats: ["Social campaign", "Brand ambassador", "Event", "Video"],
    verified: true,
    trustScore: 95,
    availabilityScore: 70,
    performanceScore: 94
  },
  {
    id: "opp-hackathon-fintech",
    organizationId: "org-hackathon-1",
    organizationNameAr: "هاكاثون التقنية المالية",
    organizationNameEn: "FinTech Hackathon SA",
    category: "hackathons",
    titleAr: "رعاية هاكاثون التقنية المالية 2026",
    titleEn: "FinTech Hackathon 2026 Sponsorship",
    descriptionAr: "هاكاثون 48 ساعة يجمع 500 مطور ومبتكر في مجال التقنية المالية مع جوائز وتغطية إعلامية.",
    descriptionEn: "48-hour hackathon gathering 500 developers and innovators in fintech with prizes and media coverage.",
    city: "Riyadh",
    startingPrice: 35000,
    currency: "SAR",
    estimatedReach: 85000,
    audience: ["Developers", "Founders", "Technology", "Finance"],
    formats: ["Naming sponsor", "Challenge track", "Mentorship", "Booth"],
    verified: true,
    trustScore: 89,
    availabilityScore: 92,
    performanceScore: 86
  },
  {
    id: "opp-hackathon-ai",
    organizationId: "org-hackathon-2",
    organizationNameAr: "تحدي الذكاء الاصطناعي",
    organizationNameEn: "AI Challenge Arabia",
    category: "hackathons",
    titleAr: "رعاية تحدي الذكاء الاصطناعي العربي",
    titleEn: "AI Challenge Arabia Sponsorship",
    descriptionAr: "مسابقة ذكاء اصطناعي افتراضية وحضورية مع مشاركين من 12 دولة عربية.",
    descriptionEn: "Hybrid AI competition with participants from 12 Arab countries.",
    city: "Riyadh",
    startingPrice: 45000,
    currency: "SAR",
    estimatedReach: 150000,
    audience: ["AI/ML", "Developers", "Students", "Technology"],
    formats: ["Title sponsor", "API challenge", "Prize pool", "Workshop"],
    verified: true,
    trustScore: 91,
    availabilityScore: 88,
    performanceScore: 87
  },
  {
    id: "opp-club-reading",
    organizationId: "org-club-1",
    organizationNameAr: "نادي القراءة السعودي",
    organizationNameEn: "Saudi Reading Club",
    category: "clubs",
    titleAr: "رعاية نادي القراءة السعودي — شراكة سنوية",
    titleEn: "Saudi Reading Club — Annual Partnership",
    descriptionAr: "نادي قراءة يضم 8,000 عضو نشط مع لقاءات شهرية وفعاليات ثقافية في 5 مدن.",
    descriptionEn: "Reading club with 8,000 active members, monthly meetups and cultural events across 5 cities.",
    city: "Riyadh",
    startingPrice: 18000,
    currency: "SAR",
    estimatedReach: 40000,
    audience: ["Culture", "Education", "Professionals", "Youth"],
    formats: ["Event sponsor", "Book recommendations", "Newsletter", "Social"],
    verified: true,
    trustScore: 88,
    availabilityScore: 95,
    performanceScore: 80
  },
  {
    id: "opp-club-tech",
    organizationId: "org-club-2",
    organizationNameAr: "نادي التقنية والابتكار",
    organizationNameEn: "Tech & Innovation Club",
    category: "clubs",
    titleAr: "شراكة مع نادي التقنية — ورش وهاكاثونات شهرية",
    titleEn: "Tech Club Partnership — Monthly workshops & hackathons",
    descriptionAr: "نادي تقني يقيم ورش عمل وهاكاثونات شهرية مع جمهور من المطورين ورواد الأعمال.",
    descriptionEn: "Tech club running monthly workshops and mini-hackathons for developers and entrepreneurs.",
    city: "Dammam",
    startingPrice: 12000,
    currency: "SAR",
    estimatedReach: 25000,
    audience: ["Developers", "Founders", "Students", "Technology"],
    formats: ["Workshop sponsor", "Booth", "Social", "Mentorship"],
    verified: true,
    trustScore: 86,
    availabilityScore: 93,
    performanceScore: 78
  },
  {
    id: "opp-gaming-streamer",
    organizationId: "org-streamer",
    organizationNameAr: "ستريمر ألعاب عربي",
    organizationNameEn: "ArabGamer Streamer",
    category: "gaming",
    titleAr: "رعاية بثوث مباشرة لستريمر ألعاب",
    titleEn: "Live stream sponsorship with top Arab gamer",
    descriptionAr: "بثوث مباشرة على تويتش ويوتيوب مع جمهور عربي شاب ومتفاعل في الألعاب.",
    descriptionEn: "Twitch & YouTube live streams with an engaged young Arab gaming audience.",
    city: "Jeddah",
    startingPrice: 20000,
    currency: "SAR",
    estimatedReach: 380000,
    audience: ["Gen Z", "Gaming", "Youth", "Students"],
    formats: ["Stream overlay", "Shoutout", "Giveaway", "Social"],
    verified: true,
    trustScore: 84,
    availabilityScore: 91,
    performanceScore: 90
  }
];

export const demoPackages: PackageTier[] = [
  {
    id: "pkg-cyber-gold",
    opportunityId: "opp-cyber-forum",
    nameAr: "الباقة الذهبية",
    nameEn: "Gold Package",
    price: 85000,
    currency: "SAR",
    quantity: 1,
    entitlements: ["Main stage presence", "Premium booth", "Logo on all materials", "500 qualified leads", "Post-event report"],
    status: "available"
  },
  {
    id: "pkg-cyber-silver",
    opportunityId: "opp-cyber-forum",
    nameAr: "الباقة الفضية",
    nameEn: "Silver Package",
    price: 45000,
    currency: "SAR",
    quantity: 3,
    entitlements: ["Panel slot", "Standard booth", "Logo on website", "200 qualified leads"],
    status: "available"
  },
  {
    id: "pkg-cyber-bronze",
    opportunityId: "opp-cyber-forum",
    nameAr: "الباقة البرونزية",
    nameEn: "Bronze Package",
    price: 18000,
    currency: "SAR",
    quantity: 5,
    entitlements: ["Logo on website", "50 attendee contacts", "Social media mention"],
    status: "available"
  },
  {
    id: "pkg-podcast-4ep",
    opportunityId: "opp-tech-podcast",
    nameAr: "باقة 4 حلقات",
    nameEn: "4-Episode Package",
    price: 24000,
    currency: "SAR",
    entitlements: ["Host-read ad (4 episodes)", "Social clip per episode", "Newsletter mention"],
    status: "available"
  },
  {
    id: "pkg-podcast-8ep",
    opportunityId: "opp-tech-podcast",
    nameAr: "باقة 8 حلقات",
    nameEn: "8-Episode Package",
    price: 42000,
    currency: "SAR",
    entitlements: ["Host-read ad (8 episodes)", "Dedicated social content", "Newsletter feature", "Bonus interview slot"],
    status: "available"
  },
  {
    id: "pkg-esports-title",
    opportunityId: "opp-esports",
    nameAr: "شريك البطولة الرئيسي",
    nameEn: "Title Tournament Partner",
    price: 45000,
    currency: "SAR",
    quantity: 1,
    entitlements: ["Title naming rights", "Arena branding", "Stream overlay", "Winner ceremony", "Social campaign"],
    status: "available"
  },
  {
    id: "pkg-esports-stream",
    opportunityId: "opp-esports",
    nameAr: "باقة البث المباشر",
    nameEn: "Stream Package",
    price: 15000,
    currency: "SAR",
    quantity: 4,
    entitlements: ["Stream overlay", "Shoutouts", "Giveaway integration"],
    status: "available"
  }
];

export const demoDeals: Deal[] = [
  {
    id: "deal-001",
    opportunityId: "opp-tech-podcast",
    campaignId: "camp-001",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-podcast",
    title: "Tech Orbit — Q4 Thought Leadership",
    counterparty: "Tech Orbit Podcast",
    amount: 24000,
    currency: "SAR",
    stage: "negotiation",
    updatedAt: "2026-08-14T11:30:00Z"
  },
  {
    id: "deal-002",
    opportunityId: "opp-university",
    campaignId: "camp-001",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-community",
    title: "Innovation Week activation",
    counterparty: "University Innovation Community",
    amount: 18000,
    currency: "SAR",
    stage: "internal_approval",
    updatedAt: "2026-08-13T08:15:00Z"
  },
  {
    id: "deal-003",
    opportunityId: "opp-youtube-creator",
    campaignId: "camp-002",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-yt-creator",
    title: "TechReview Arabia — Product Launch",
    counterparty: "TechReview Arabia",
    amount: 15000,
    currency: "SAR",
    stage: "contract_draft",
    updatedAt: "2026-08-12T14:00:00Z"
  },
  {
    id: "deal-004",
    opportunityId: "opp-jeddah-food-fest",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-jeddah-events",
    title: "Jeddah Food Fest — Brand Activation",
    counterparty: "Jeddah Food Festival",
    amount: 120000,
    currency: "SAR",
    stage: "funding_pending",
    updatedAt: "2026-08-10T09:45:00Z"
  },
  {
    id: "deal-005",
    opportunityId: "opp-esports",
    buyerOrgId: "org-demo-brand",
    sellerOrgId: "org-esports",
    title: "Saudi Gaming League — Summer Cup",
    counterparty: "Saudi Gaming League",
    amount: 45000,
    currency: "SAR",
    stage: "completed",
    updatedAt: "2026-07-28T16:20:00Z"
  }
];

export const demoNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "deal_update",
    titleAr: "تحديث صفقة",
    titleEn: "Deal Update",
    bodyAr: "صفقة Tech Orbit انتقلت إلى مرحلة التفاوض",
    bodyEn: "Tech Orbit deal moved to negotiation stage",
    read: false,
    createdAt: "2026-08-14T11:30:00Z",
    link: "/deals/deal-001"
  },
  {
    id: "notif-2",
    type: "new_match",
    titleAr: "فرصة مطابقة جديدة",
    titleEn: "New Match Found",
    bodyAr: "تم العثور على 3 فرص جديدة تتطابق مع حملتك",
    bodyEn: "3 new opportunities match your campaign criteria",
    read: false,
    createdAt: "2026-08-14T09:00:00Z",
    link: "/planner"
  },
  {
    id: "notif-3",
    type: "verification",
    titleAr: "تحقق مكتمل",
    titleEn: "Verification Complete",
    bodyAr: "تم التحقق من جهة بودكاست مدار التقنية بنجاح",
    bodyEn: "Tech Orbit Podcast organization verification completed",
    read: true,
    createdAt: "2026-08-13T15:00:00Z"
  },
  {
    id: "notif-4",
    type: "deal_update",
    titleAr: "عرض جديد مستلم",
    titleEn: "New Proposal Received",
    bodyAr: "تلقيت عرضًا جديدًا لصفقة Innovation Week",
    bodyEn: "New proposal received for Innovation Week deal",
    read: true,
    createdAt: "2026-08-12T10:00:00Z",
    link: "/deals/deal-002"
  },
  {
    id: "notif-5",
    type: "system",
    titleAr: "مرحبًا بك في SponsorLoop",
    titleEn: "Welcome to SponsorLoop",
    bodyAr: "ابدأ باستكشاف الفرص أو أنشئ حملتك الأولى",
    bodyEn: "Start by exploring opportunities or creating your first campaign",
    read: true,
    createdAt: "2026-08-10T08:00:00Z"
  }
];

export const demoDealMessages: DealMessage[] = [
  {
    id: "msg-1",
    dealId: "deal-001",
    senderName: "Tech Orbit Podcast",
    senderRole: "seller",
    message: "Thank you for your interest. We can offer a bonus social clip package for the 4-episode deal.",
    createdAt: "2026-08-14T11:30:00Z"
  },
  {
    id: "msg-2",
    dealId: "deal-001",
    senderName: "Demo Brand",
    senderRole: "buyer",
    message: "That sounds great. Can you share the audience demographics breakdown?",
    createdAt: "2026-08-14T10:15:00Z"
  },
  {
    id: "msg-3",
    dealId: "deal-001",
    senderName: "System",
    senderRole: "system",
    message: "Deal created and moved to negotiation stage.",
    createdAt: "2026-08-13T16:00:00Z"
  },
  {
    id: "msg-4",
    dealId: "deal-002",
    senderName: "University Innovation Community",
    senderRole: "seller",
    message: "We have confirmed the booth location and workshop slot for your team.",
    createdAt: "2026-08-13T08:15:00Z"
  },
  {
    id: "msg-5",
    dealId: "deal-002",
    senderName: "System",
    senderRole: "system",
    message: "Deal advanced to approval stage.",
    createdAt: "2026-08-12T14:00:00Z"
  }
];

export const demoReviews: Review[] = [
  {
    id: "rev-1",
    dealId: "deal-005",
    rating: 5,
    comment: "Excellent partnership! Great audience engagement and professional execution.",
    reviewerName: "Demo Brand",
    createdAt: "2026-07-29T10:00:00Z"
  }
];

export const demoSponsorshipRequests: SponsorshipRequest[] = [
  {
    id: "req-001",
    organizationNameAr: "نادي رياضي مجتمعي",
    organizationNameEn: "Community Sports Club",
    category: "sports",
    titleAr: "نبحث عن راعٍ رسمي لموسم الدوري المحلي 2026",
    titleEn: "Seeking official sponsor for 2026 local league season",
    descriptionAr: "نادي رياضي مجتمعي في جدة يضم 12 فريقًا، يبحث عن شريك رسمي يحصل على حقوق التسمية والعلامة على القمصان والتفعيل الجماهيري.",
    descriptionEn: "Jeddah-based community sports club with 12 teams, seeking official partner for naming rights, jersey branding and fan activation.",
    city: "Jeddah",
    budgetRange: "50K–100K SAR",
    audienceSize: 120000,
    status: "open",
    createdAt: "2026-08-12T08:00:00Z"
  },
  {
    id: "req-002",
    organizationNameAr: "مهرجان الابتكار التقني",
    organizationNameEn: "Tech Innovation Festival",
    category: "events",
    titleAr: "نحتاج رعاة لمهرجان الابتكار التقني — 3 مستويات متاحة",
    titleEn: "Sponsors needed for Tech Innovation Festival — 3 tiers available",
    descriptionAr: "مهرجان تقني لمدة 3 أيام في الرياض يستقطب 5,000 زائر من المطورين والمؤسسين والمستثمرين. باقات ذهبية وفضية وبرونزية متاحة.",
    descriptionEn: "3-day tech festival in Riyadh attracting 5,000 visitors from developers, founders and investors. Gold, Silver and Bronze packages available.",
    city: "Riyadh",
    budgetRange: "30K–150K SAR",
    audienceSize: 50000,
    status: "open",
    createdAt: "2026-08-10T14:00:00Z"
  },
  {
    id: "req-003",
    organizationNameAr: "بودكاست صحة وعافية",
    organizationNameEn: "Health & Wellness Podcast",
    category: "podcasts",
    titleAr: "نبحث عن راعٍ لموسم جديد من بودكاست صحي متخصص",
    titleEn: "Seeking sponsor for new season of specialized health podcast",
    descriptionAr: "بودكاست صحي يبث أسبوعيًا يستمع إليه 60,000 مستمع شهريًا. نبحث عن شريك في مجال الصحة أو اللياقة.",
    descriptionEn: "Weekly health podcast with 60,000 monthly listeners. Looking for a health or fitness brand partner.",
    city: "Riyadh",
    budgetRange: "15K–40K SAR",
    audienceSize: 60000,
    status: "open",
    createdAt: "2026-08-09T10:00:00Z"
  },
  {
    id: "req-004",
    organizationNameAr: "رياضية سعودية — عداءة",
    organizationNameEn: "Saudi Athlete — Track & Field",
    category: "athletes",
    titleAr: "رياضية سعودية تبحث عن راعٍ رياضي شخصي",
    titleEn: "Saudi track & field athlete seeking personal sports sponsor",
    descriptionAr: "عداءة سعودية مشاركة في بطولات دولية تبحث عن راعٍ لتغطية التدريب والمعدات والسفر مقابل تمثيل العلامة.",
    descriptionEn: "Saudi track athlete competing internationally, seeking sponsor for training, equipment and travel in exchange for brand representation.",
    city: "Dammam",
    budgetRange: "20K–60K SAR",
    audienceSize: 95000,
    status: "open",
    createdAt: "2026-08-08T16:00:00Z"
  },
  {
    id: "req-005",
    organizationNameAr: "نادي القراءة الثقافي",
    organizationNameEn: "Cultural Reading Club",
    category: "clubs",
    titleAr: "نادي ثقافي يبحث عن شريك لرعاية فعاليات القراءة الشهرية",
    titleEn: "Cultural club seeking partner for monthly reading events",
    descriptionAr: "نادي قراءة في المدينة المنورة يضم 3,000 عضو يبحث عن شريك سنوي لدعم الفعاليات الثقافية.",
    descriptionEn: "Madinah reading club with 3,000 members seeking annual partner for cultural events.",
    city: "Madinah",
    budgetRange: "10K–25K SAR",
    audienceSize: 15000,
    status: "open",
    createdAt: "2026-08-07T09:00:00Z"
  }
];

export const demoSuccessStories: SuccessStory[] = [
  {
    id: "story-1",
    brandNameAr: "شركة تقنية رائدة",
    brandNameEn: "Leading Tech Corp",
    partnerNameAr: "بودكاست مدار التقنية",
    partnerNameEn: "Tech Orbit Podcast",
    category: "podcasts",
    quoteAr: "حققنا 340% ROI على رعاية 4 حلقات. المنصة سهّلت كل شيء من الاكتشاف إلى القياس.",
    quoteEn: "We achieved 340% ROI on a 4-episode sponsorship. The platform streamlined everything from discovery to measurement.",
    metric: "340%",
    metricLabel: "ROI"
  },
  {
    id: "story-2",
    brandNameAr: "علامة رياضية سعودية",
    brandNameEn: "Saudi Sports Brand",
    partnerNameAr: "سارة الحربي — سباحة أولمبية",
    partnerNameEn: "Sara Al-Harbi — Olympic Swimmer",
    category: "athletes",
    quoteAr: "رعاية الرياضيين الأفراد كانت مستحيلة بدون وسيط. SponsorLoop وصلنا بالرياضية المثالية في أسبوع.",
    quoteEn: "Individual athlete sponsorship was impossible without a middleman. SponsorLoop connected us with the perfect athlete in one week.",
    metric: "1.2M",
    metricLabel: "Reach"
  },
  {
    id: "story-3",
    brandNameAr: "بنك رقمي",
    brandNameEn: "Digital Bank",
    partnerNameAr: "هاكاثون التقنية المالية",
    partnerNameEn: "FinTech Hackathon SA",
    category: "hackathons",
    quoteAr: "رعاية الهاكاثون جلبت لنا 200 مطور مؤهل لبرنامج التوظيف و 85,000 وصول اجتماعي.",
    quoteEn: "Hackathon sponsorship brought us 200 qualified developers for our hiring pipeline and 85K social reach.",
    metric: "200",
    metricLabel: "Qualified Leads"
  },
  {
    id: "story-4",
    brandNameAr: "شركة أغذية",
    brandNameEn: "Food Corp SA",
    partnerNameAr: "مهرجان جدة للطعام",
    partnerNameEn: "Jeddah Food Festival",
    category: "events",
    quoteAr: "المنصة ساعدتنا نقارن بين 12 فرصة ونختار الأنسب. وفّرنا 40% من وقت البحث.",
    quoteEn: "The platform helped us compare 12 opportunities and choose the best fit. Saved 40% of our research time.",
    metric: "40%",
    metricLabel: "Time Saved"
  }
];
