import { createHash } from "node:crypto";
import { query } from "./db";

export const DEAL_STAGES = ["inquiry","offer_submitted","rights_holder_review","negotiation","internal_approval","contract_draft","seller_approved","buyer_approved","signature_pending","signed","funding_pending","funded","activation_planning","creative_review","live","evidence_submitted","milestone_approved","settlement_pending","settled","performance_reporting","completed"] as const;

const statements = [
`ALTER TABLE deals DROP CONSTRAINT IF EXISTS deals_stage_check`,
`ALTER TABLE deals ALTER COLUMN stage SET DEFAULT 'inquiry'`,
`CREATE TABLE IF NOT EXISTS workflow_policies(policy_key text PRIMARY KEY,version integer NOT NULL DEFAULT 1,config jsonb NOT NULL,sources jsonb NOT NULL DEFAULT '[]',active boolean NOT NULL DEFAULT true,updated_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS deal_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_id uuid NOT NULL REFERENCES deals(id) ON DELETE CASCADE,organization_id uuid NOT NULL REFERENCES organizations(id),category text NOT NULL,object_key text NOT NULL UNIQUE,file_name text NOT NULL,content_type text NOT NULL,size_bytes integer NOT NULL,status text NOT NULL DEFAULT 'uploaded',created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS deal_proposals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_id uuid NOT NULL REFERENCES deals(id) ON DELETE CASCADE,version integer NOT NULL,amount numeric NOT NULL,currency text NOT NULL DEFAULT 'SAR',deliverables jsonb NOT NULL DEFAULT '[]',timeline jsonb NOT NULL DEFAULT '[]',exclusivity text,notes text,created_by uuid REFERENCES users(id),status text NOT NULL DEFAULT 'submitted',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(deal_id,version))`,
`CREATE TABLE IF NOT EXISTS deal_contracts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_id uuid NOT NULL UNIQUE REFERENCES deals(id) ON DELETE CASCADE,template_key text NOT NULL,version integer NOT NULL DEFAULT 1,terms jsonb NOT NULL,status text NOT NULL DEFAULT 'draft',seller_approved_at timestamptz,buyer_approved_at timestamptz,signature_provider text,signature_reference text,signature_hash text,created_at timestamptz NOT NULL DEFAULT now(),signed_at timestamptz)`,
`CREATE TABLE IF NOT EXISTS deal_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_id uuid NOT NULL REFERENCES deals(id) ON DELETE CASCADE,organization_id uuid NOT NULL REFERENCES organizations(id),approval_type text NOT NULL,decision text NOT NULL,notes text,actor_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS deal_payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_id uuid NOT NULL REFERENCES deals(id) ON DELETE CASCADE,milestone text NOT NULL,amount numeric NOT NULL,currency text NOT NULL DEFAULT 'SAR',provider text,external_reference text,status text NOT NULL DEFAULT 'pending_review',proof_object_key text,created_at timestamptz NOT NULL DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS email_outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_id uuid REFERENCES deals(id) ON DELETE CASCADE,to_email text NOT NULL,subject text NOT NULL,body_text text NOT NULL,status text NOT NULL DEFAULT 'queued',provider_reference text,error text,created_at timestamptz NOT NULL DEFAULT now(),sent_at timestamptz)`,
`CREATE TABLE IF NOT EXISTS deal_disputes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deal_id uuid NOT NULL REFERENCES deals(id) ON DELETE CASCADE,opened_by_org_id uuid NOT NULL REFERENCES organizations(id),reason text NOT NULL,description text NOT NULL,evidence jsonb NOT NULL DEFAULT '[]',status text NOT NULL DEFAULT 'open',resolution text,created_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz)`,
`INSERT INTO workflow_policies(policy_key,version,config,sources) VALUES('sponsorship_deal_v1',1,'{"stages":["inquiry","offer_submitted","rights_holder_review","negotiation","internal_approval","contract_draft","seller_approved","buyer_approved","signature_pending","signed","funding_pending","funded","activation_planning","creative_review","live","evidence_submitted","milestone_approved","settlement_pending","settled","performance_reporting","completed"],"platformFeePercent":5,"paymentNotice":"SponsorLoop does not hold funds until a licensed PSP is connected","signatureNotice":"Platform approvals and hash audit are not a qualified external electronic signature"}','[{"name":"Anvara","url":"https://www.anvara.com/"},{"name":"Sponex","url":"https://sponex.app/"},{"name":"Saudi National PKI","url":"https://dga.gov.sa/ar/node/2076"}]') ON CONFLICT(policy_key) DO NOTHING`
];
export async function ensureOperations(){for(const sql of statements)await query(sql)}
export function contractHash(id:string,terms:unknown){return createHash("sha256").update(`${id}:${JSON.stringify(terms)}`).digest("hex")}
export async function assertDealAccess(dealId:string,organizationId:string,isAdmin=false){const r=await query<any>(`SELECT * FROM deals WHERE id=$1 AND ($3::boolean OR buyer_org_id=$2 OR seller_org_id=$2)`,[dealId,organizationId,isAdmin]);return r.rows[0]||null}
